apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-videos
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-videos
  template:
    metadata:
      labels:
        app: ms-videos
    spec:
      containers:
        - name: ms-videos
          image: ms-videos:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "500m"
              memory: "8000Mi"
            limits:
              cpu: "2000m"
              memory: "8000Mi"
          env:
            - name: RABBITMQ_URL
              value: amqp://guest:guest@192.168.4.13:5672/
            - name: MINIO_ENDPOINT
              value: 192.168.4.13:9000
            - name: MINIO_ACCESS_KEY
              value: minioadmin
            - name: MINIO_SECRET_KEY
              value: minioadmin
            - name: MINIO_BUCKET
              value: videos
            - name: GO_ENV
              value: development
            - name: LOG_LEVEL
              value: info

---
apiVersion: v1
kind: Service
metadata:
  name: ms-videos
  namespace: default
spec:
  selector:
    app: ms-videos
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ms-videos-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ms-videos
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70
